/**
 * Common misspelling corrections and word frequency data.
 * These provide instant, high-quality suggestions without trie traversal.
 */

/** Map of common misspellings -> correct spelling */
export const COMMON_MISSPELLINGS: ReadonlyMap<string, string[]> = new Map([
  // Top 100+ most common English misspellings
  ['absense', ['absence']],
  ['accidentaly', ['accidentally']],
  ['accomodate', ['accommodate']],
  ['acheive', ['achieve']],
  ['acknowlege', ['acknowledge']],
  ['acquaintence', ['acquaintance']],
  ['adress', ['address']],
  ['agressive', ['aggressive']],
  ['aledge', ['allege']],
  ['apparantly', ['apparently']],
  ['arguement', ['argument']],
  ['assasinate', ['assassinate']],
  ['basicly', ['basically']],
  ['begining', ['beginning']],
  ['beleive', ['believe']],
  ['buisness', ['business']],
  ['calender', ['calendar']],
  ['catagory', ['category']],
  ['cemetary', ['cemetery']],
  ['changable', ['changeable']],
  ['collegue', ['colleague']],
  ['comming', ['coming']],
  ['commited', ['committed']],
  ['comparision', ['comparison']],
  ['concieve', ['conceive']],
  ['concensus', ['consensus']],
  ['consistant', ['consistent']],
  ['definately', ['definitely']],
  ['definitly', ['definitely']],
  ['dependant', ['dependent']],
  ['desparate', ['desperate']],
  ['develope', ['develop']],
  ['dilemna', ['dilemma']],
  ['disapear', ['disappear']],
  ['dissapoint', ['disappoint']],
  ['embarass', ['embarrass']],
  ['enviroment', ['environment']],
  ['exagerate', ['exaggerate']],
  ['excercise', ['exercise']],
  ['existance', ['existence']],
  ['expirience', ['experience']],
  ['facinate', ['fascinate']],
  ['firey', ['fiery']],
  ['foriegn', ['foreign']],
  ['freind', ['friend']],
  ['goverment', ['government']],
  ['grammer', ['grammar']],
  ['gaurd', ['guard']],
  ['happend', ['happened']],
  ['harrass', ['harass']],
  ['heighth', ['height']],
  ['heros', ['heroes']],
  ['humourous', ['humorous']],
  ['hygeine', ['hygiene']],
  ['ignorence', ['ignorance']],
  ['immediatly', ['immediately']],
  ['incidently', ['incidentally']],
  ['independant', ['independent']],
  ['indispensible', ['indispensable']],
  ['innoculate', ['inoculate']],
  ['inteligence', ['intelligence']],
  ['intresting', ['interesting']],
  ['irresistable', ['irresistible']],
  ['jewlery', ['jewelry']],
  ['judgement', ['judgment']],
  ['knowlege', ['knowledge']],
  ['liason', ['liaison']],
  ['libary', ['library']],
  ['liesure', ['leisure']],
  ['maintainance', ['maintenance']],
  ['millenium', ['millennium']],
  ['minature', ['miniature']],
  ['mischievious', ['mischievous']],
  ['mispell', ['misspell']],
  ['neccessary', ['necessary']],
  ['noticable', ['noticeable']],
  ['occassion', ['occasion']],
  ['occurence', ['occurrence']],
  ['occured', ['occurred']],
  ['oficial', ['official']],
  ['oportunity', ['opportunity']],
  ['paralel', ['parallel']],
  ['parliment', ['parliament']],
  ['percieve', ['perceive']],
  ['perseverence', ['perseverance']],
  ['personell', ['personnel']],
  ['posession', ['possession']],
  ['prefered', ['preferred']],
  ['privelege', ['privilege']],
  ['pronounciation', ['pronunciation']],
  ['publically', ['publicly']],
  ['que', ['queue']],
  ['quik', ['quick']],
  ['realy', ['really']],
  ['reccomend', ['recommend']],
  ['recieve', ['receive']],
  ['refered', ['referred']],
  ['referance', ['reference']],
  ['relevent', ['relevant']],
  ['religous', ['religious']],
  ['repitition', ['repetition']],
  ['resistence', ['resistance']],
  ['responsable', ['responsible']],
  ['restaraunt', ['restaurant']],
  ['rythm', ['rhythm']],
  ['seige', ['siege']],
  ['sentance', ['sentence']],
  ['seperate', ['separate']],
  ['sergent', ['sergeant']],
  ['sieze', ['seize']],
  ['similer', ['similar']],
  ['sinceerly', ['sincerely']],
  ['speach', ['speech']],
  ['strenght', ['strength']],
  ['succesful', ['successful']],
  ['supercede', ['supersede']],
  ['surley', ['surely']],
  ['surprize', ['surprise']],
  ['tempature', ['temperature']],
  ['therefor', ['therefore']],
  ['threshhold', ['threshold']],
  ['tommorow', ['tomorrow']],
  ['tounge', ['tongue']],
  ['truely', ['truly']],
  ['tyrany', ['tyranny']],
  ['underate', ['underrate']],
  ['untill', ['until']],
  ['useable', ['usable']],
  ['vaccuum', ['vacuum']],
  ['vegetable', ['vegetable']],
  ['visable', ['visible']],
  ['wether', ['whether']],
  ['wierd', ['weird']],
  ['writting', ['writing']],

  // Common programming misspellings
  ['acessor', ['accessor']],
  ['asyncronous', ['asynchronous']],
  ['authentification', ['authentication']],
  ['calback', ['callback']],
  ['cancell', ['cancel']],
  ['concurency', ['concurrency']],
  ['configration', ['configuration']],
  ['deamon', ['daemon']],
  ['depricated', ['deprecated']],
  ['derefrence', ['dereference']],
  ['deserialization', ['deserialization']],
  ['endpont', ['endpoint']],
  ['excute', ['execute']],
  ['formater', ['formatter']],
  ['implemntation', ['implementation']],
  ['initalize', ['initialize']],
  ['iterater', ['iterator']],
  ['lisen', ['listen']],
  ['mesage', ['message']],
  ['middlewear', ['middleware']],
  ['parametr', ['parameter']],
  ['recuring', ['recurring']],
  ['refrence', ['reference']],
  ['rendrer', ['renderer']],
  ['responce', ['response']],
  ['requirment', ['requirement']],
  ['runing', ['running']],
  ['scafolding', ['scaffolding']],
  ['serialze', ['serialize']],
  ['singelton', ['singleton']],
  ['syncronize', ['synchronize']],
  ['tempalte', ['template']],
  ['timestap', ['timestamp']],
  ['transcation', ['transaction']],
  ['utiliy', ['utility']],
  ['validaton', ['validation']],
  ['variabel', ['variable']],
])

/**
 * High-frequency English words — used to boost suggestion ranking.
 * Words in this set are preferred when multiple suggestions have the same edit distance.
 */
export const HIGH_FREQUENCY_WORDS: ReadonlySet<string> = new Set([
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i',
  'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at',
  'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she',
  'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what',
  'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me',
  'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know', 'take',
  'people', 'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other',
  'than', 'then', 'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also',
  'back', 'after', 'use', 'two', 'how', 'our', 'work', 'first', 'well', 'way',
  'even', 'new', 'want', 'because', 'any', 'these', 'give', 'day', 'most', 'us',
  'great', 'find', 'here', 'thing', 'many', 'still', 'between', 'name', 'should',
  'very', 'each', 'much', 'being', 'did', 'has', 'had', 'was', 'were', 'been',
  'said', 'does', 'own', 'run', 'set', 'put', 'end', 'why', 'try', 'ask',
  'men', 'need', 'move', 'live', 'old', 'too', 'same', 'tell', 'help', 'every',
  'few', 'long', 'little', 'big', 'small', 'open', 'keep', 'start', 'never', 'change',
  // Common programming words
  'function', 'return', 'value', 'type', 'string', 'number', 'error', 'data', 'file',
  'list', 'call', 'check', 'test', 'code', 'build', 'read', 'write', 'close',
  'true', 'false', 'null', 'class', 'method', 'object', 'array', 'table', 'index',
  'load', 'save', 'send', 'path', 'text', 'line', 'word', 'page', 'link',
  'user', 'name', 'size', 'kind', 'sort', 'search', 'query', 'result', 'state',
  'event', 'handler', 'response', 'request', 'server', 'client', 'config', 'option',
  'message', 'update', 'create', 'delete', 'insert', 'select', 'parse', 'format',
  'input', 'output', 'stream', 'buffer', 'cache', 'queue', 'stack', 'store',
  'quick', 'fast', 'slow', 'high', 'low', 'next', 'last', 'left', 'right',
])
